language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build
  - cargo build --features "json"
  - cargo build --features "yaml"
  - cargo build --features "json yaml"
cache: cargo
