name: CI
on:
  - push
  - pull_request
jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - 1.56.1
          - stable
          - beta
          - nightly
        os:
          - macOS-10.15
          - macOS-11
          - macOS-12
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2016
          - windows-2019
          - windows-2022
    steps:

    - uses: actions/checkout@v2

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Build (with "yaml" feature)
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features yaml

    - name: Build (with "json" feature)
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features json

    - name: Build (with all features)
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features

  security-audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/audit-check@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
