name: CI
on:
  - push
  - pull_request
jobs:
  build:
    name: ${{ matrix.os }} | ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - 1.36.0
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:

    - uses: actions/checkout@v1

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Build (with "yaml" feature)
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features yaml

    - name: Build (with "json" feature)
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features json

    - name: Build (with all features)
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features
