name: CI
on:
  - push
  - pull_request
jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - 1.64.0
          - stable
        # https://github.com/actions/virtual-environments#available-environments
        os:
          - macOS-11
          - macOS-12
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
    steps:

    - uses: actions/checkout@v3

    - name: Install ${{ matrix.rust }} toolchain
      uses: dtolnay/rust-toolchain@master
      with:
          toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build

    - name: Build (with "json" feature)
      run: cargo build --features json

    - name: Build (with all features)
      run: cargo build --all-features

    - name: Build (with no features)
      run: cargo build --no-default-features

  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rustsec/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
