# NOTE: this is stolen from cargo-dist workflow file

# Publishes a release to crates.io
#
# To trigger this:
#
# - go to Actions > Publish
# - click the Run Workflow dropdown in the top-right
name: Publish
on: workflow_dispatch
jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
